const ACTIONS = {
    GET_TASKS: "GET_TASKS",
    ADD_TASK: "ADD_TASK",
    DELETE_TASK: "DELETE_TASK",
    DONE_TASK: "DONE_TASK",
    EDIT_TASK: "EDIT_TASK",
    CLEAR_ALL: "CLEAR_ALL",
    SORT_BY_NAME: "SORT_BY_NAME",
    LOADING: "LOADING",
    FAILED: "FAILED",
    SUCCESSFUL: "SUCCESSFUL",
    SEARCH: "SEARCH",
    HIDE_DONE: "HIDE_DONE",
    SAVE_DELETED: "SAVE_DELETED"
};

export default ACTIONS;
